# Generated by Django 4.0.5 on 2022-08-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediHealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='ConfirmPassword',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Password',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AlterModelTable(
            name='doctor',
            table='DoctorTable',
        ),
    ]
