# Generated by Django 4.0.5 on 2022-08-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediHealer', '0002_doctor_confirmpassword_doctor_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Password',
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='DEFAULT VALUE', max_length=1050),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='ConfirmPassword',
            field=models.CharField(default='DEFAULT VALUE', max_length=1050),
        ),
    ]
