# Generated by Django 4.0.5 on 2022-08-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediHealer', '0004_remove_doctor_confirmpassword_resetpwdtokens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResetPwdTokens',
        ),
    ]
