# Generated by Django 4.0.5 on 2022-08-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediHealer', '0005_delete_resetpwdtokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=15)),
                ('lastname', models.TextField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('appfor', models.TextField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'appointmentTable',
            },
        ),
    ]
