# Generated by Django 4.0.5 on 2022-09-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediHealer', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Address',
            field=models.TextField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='MedicalFrom',
            field=models.TextField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='WorkingMedical',
            field=models.TextField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
