# Generated by Django 4.0.5 on 2022-09-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediHealer', '0008_doctor_address_doctor_medicalfrom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=15)),
                ('FirstName', models.TextField(max_length=50)),
                ('LastName', models.TextField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('NID', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.TextField(default='DEFAULT VALUE', max_length=100)),
                ('password', models.CharField(default='DEFAULT VALUE', max_length=1050)),
            ],
            options={
                'db_table': 'patienttable',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='Specialized',
            field=models.TextField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
